# fly.toml app configuration file generated for squad-roster on 2023-07-19T18:47:42+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "squad-roster"
primary_region = "arn"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "5000"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
